/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentinformationsystem;

/**
 *
 * @author Meem
 */
import java.sql.*;
import java.awt.*;
import javax.swing.*;
import java.util.Date;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.image.BufferedImage;
import java.io.FileOutputStream;
import java.io.File;
import javax.imageio.ImageIO;
//import java.awt.PrintGraphics.*;




//import java.util.logging.Level;
//import java.text.*;
//import java.awt.print.*;

//import java.util.logging.Logger;


public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
        
        //Make the frame fullscreen
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        int width = (int) toolkit.getScreenSize().getWidth();
        int height = (int) toolkit.getScreenSize().getHeight();
        this.setSize(width, height);
    }
    
    //Take screenshot
    public static BufferedImage getScreenShot(Component component){
        BufferedImage image = new BufferedImage(component.getWidth(), component.getHeight(), BufferedImage.TYPE_INT_RGB);
        component.paint(image.getGraphics());
        return image;
    }
    
    //Save screenshot in png format
    public static void saveScreenShot(Component component, String filename) throws Exception{
        BufferedImage img = getScreenShot(component);
        ImageIO.write(img, "png", new File(filename));
    }
    
    //Get ID from login
    public Student(int ID) {
        initComponents();
        
        //Create database connection
        dbMysqlConnection ob = new dbMysqlConnection();
        Connection conn = null; 
	conn = ob.getConnection();
        
        Statement statement1 = null;
        Statement statement2 = null;
        ResultSet resultSet1 = null;
        ResultSet resultSet2 = null;
       
        //SQL query 
        String query1 = "select id, name, fa_name, mo_name, mobile, mail, bl_gr, address, dof from st_general where id = '"+ID+"'";
        String query2 = "select id, prog, sem, cgpa, res_st from st_academic where id = '"+ID+"'";
        
        try{
            statement1 = conn.createStatement();
            statement2 = conn.createStatement();
            resultSet1 = statement1.executeQuery(query1);
            resultSet2 = statement2.executeQuery(query2);
            
            //Show general information
            if(resultSet1.next()) {
                String Id = resultSet1.getString("id");
                jLabel_ShowId.setText(Id);
                String name = resultSet1.getString("name");
                jLabel_ShowName.setText(name);
                String father_name = resultSet1.getString("fa_name");
                jLabel_ShowFatherName.setText(father_name);
                String mother_name = resultSet1.getString("mo_name");
                jLabel_ShowMotherName.setText(mother_name);
                String mobile = resultSet1.getString("mobile");
                jLabel_ShowMobile.setText(mobile);
                String email = resultSet1.getString("mail");
                jLabel_ShowEmail.setText(email);
                String blood_group = resultSet1.getString("bl_gr");
                jLabel_ShowBloodGroup.setText(blood_group);
                String birth_date = resultSet1.getString("dof");
                jLabel_ShowDateOfBirth.setText(birth_date);
                String address = resultSet1.getString("address");
                jTextArea_Address.setText(address);
            }
            
            //Show academic information
            if(resultSet2.next()) {
                String program = resultSet2.getString("prog");
                jLabel_ShowProgram.setText(program);
                String semester = resultSet2.getString("sem");
                jLabel_ShowSemester.setText(semester);
                String cgpa = resultSet2.getString("cgpa");
                jLabel_ShowCGPA.setText(cgpa);
                String resultstatus = resultSet2.getString("res_st");
                jLabel_ShowResultStatus.setText(resultstatus);
            }
            
            statement1.close();
            statement2.close();
            conn.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jPanel_Base = new javax.swing.JPanel();
        jPanel_Title = new javax.swing.JPanel();
        jLabel_Title = new javax.swing.JLabel();
        jPanel_Top = new javax.swing.JPanel();
        jLabel_Top = new javax.swing.JLabel();
        jPanel_Side = new javax.swing.JPanel();
        jButton_Logout = new javax.swing.JButton();
        jButton_Pdf = new javax.swing.JButton();
        jButton_Screenshot = new javax.swing.JButton();
        jTabbedPane_Menu = new javax.swing.JTabbedPane();
        jPanel_Information = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel_Id = new javax.swing.JLabel();
        jLabel_Name = new javax.swing.JLabel();
        jLabel_FatherName = new javax.swing.JLabel();
        jLabel_MotherName = new javax.swing.JLabel();
        jLabel_DateOfBirth = new javax.swing.JLabel();
        jLabel_Mobile = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jLabel_BloodGroup = new javax.swing.JLabel();
        jLabel_Program = new javax.swing.JLabel();
        jLabel_Semester = new javax.swing.JLabel();
        jLabel_CGPA = new javax.swing.JLabel();
        jLabel_ResultStatus = new javax.swing.JLabel();
        jLabel_Message = new javax.swing.JLabel();
        jLabel_ShowProgram = new javax.swing.JLabel();
        jLabel_ShowSemester = new javax.swing.JLabel();
        jLabel_ShowCGPA = new javax.swing.JLabel();
        jLabel_ShowResultStatus = new javax.swing.JLabel();
        jLabel_ShowId = new javax.swing.JLabel();
        jLabel_ShowName = new javax.swing.JLabel();
        jLabel_ShowFatherName = new javax.swing.JLabel();
        jLabel_ShowMotherName = new javax.swing.JLabel();
        jLabel_ShowMobile = new javax.swing.JLabel();
        jLabel_ShowEmail = new javax.swing.JLabel();
        jLabel_ShowBloodGroup = new javax.swing.JLabel();
        jScrollPane_Address = new javax.swing.JScrollPane();
        jTextArea_Address = new javax.swing.JTextArea();
        jLabel_ShowDateOfBirth = new javax.swing.JLabel();
        jLabel_Address = new javax.swing.JLabel();
        jLabel_Icon = new javax.swing.JLabel();
        jPanel_Bottom = new javax.swing.JPanel();
        jLabel_Bottom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student Module");

        jPanel_Title.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_Title.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Title.setText("STUDENT MODULE");

        javax.swing.GroupLayout jPanel_TitleLayout = new javax.swing.GroupLayout(jPanel_Title);
        jPanel_Title.setLayout(jPanel_TitleLayout);
        jPanel_TitleLayout.setHorizontalGroup(
            jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TitleLayout.createSequentialGroup()
                .addComponent(jLabel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_TitleLayout.setVerticalGroup(
            jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitleLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_Top.setBackground(new java.awt.Color(102, 102, 102));

        jLabel_Top.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Top.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Top.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_Top.setText("Phone: 01782390567, 02943856   Email:stuinfo@gmail.com");

        javax.swing.GroupLayout jPanel_TopLayout = new javax.swing.GroupLayout(jPanel_Top);
        jPanel_Top.setLayout(jPanel_TopLayout);
        jPanel_TopLayout.setHorizontalGroup(
            jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TopLayout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel_Top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_TopLayout.setVerticalGroup(
            jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Top, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_Side.setBackground(new java.awt.Color(102, 102, 102));

        jButton_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformationsystem/Icon/logout.png"))); // NOI18N
        jButton_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogoutActionPerformed(evt);
            }
        });

        jButton_Pdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformationsystem/Icon/pdf.png"))); // NOI18N
        jButton_Pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PdfActionPerformed(evt);
            }
        });

        jButton_Screenshot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformationsystem/Icon/screenshot.png"))); // NOI18N
        jButton_Screenshot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ScreenshotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_SideLayout = new javax.swing.GroupLayout(jPanel_Side);
        jPanel_Side.setLayout(jPanel_SideLayout);
        jPanel_SideLayout.setHorizontalGroup(
            jPanel_SideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_SideLayout.createSequentialGroup()
                        .addComponent(jButton_Pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_SideLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel_SideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Screenshot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel_SideLayout.setVerticalGroup(
            jPanel_SideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SideLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton_Pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Screenshot, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane_Menu.setBackground(new java.awt.Color(153, 153, 153));
        jTabbedPane_Menu.setForeground(new java.awt.Color(51, 51, 51));
        jTabbedPane_Menu.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        jPanel_Information.setBackground(new java.awt.Color(204, 204, 204));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel_Id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Id.setText("ID:");

        jLabel_Name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Name.setText("Name:");

        jLabel_FatherName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_FatherName.setText("Father's Name:");

        jLabel_MotherName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_MotherName.setText("Mother's Name:");

        jLabel_DateOfBirth.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_DateOfBirth.setText("Date of Birth:");

        jLabel_Mobile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Mobile.setText("Mobile:");

        jLabel_Email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Email.setText("Email:");

        jLabel_BloodGroup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_BloodGroup.setText("Blood Group:");

        jLabel_Program.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Program.setText("Program:");

        jLabel_Semester.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Semester.setText("Semester:");

        jLabel_CGPA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_CGPA.setText("CGPA:");

        jLabel_ResultStatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_ResultStatus.setText("Result Status:");

        jLabel_Message.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Message.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformationsystem/Icon/error.png"))); // NOI18N
        jLabel_Message.setText("For any problem, contact with the admin");

        jLabel_ShowProgram.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel_ShowSemester.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel_ShowCGPA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel_ShowResultStatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel_ShowId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel_ShowName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel_ShowFatherName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel_ShowMotherName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel_ShowMobile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel_ShowEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel_ShowBloodGroup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextArea_Address.setEditable(false);
        jTextArea_Address.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea_Address.setColumns(20);
        jTextArea_Address.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextArea_Address.setRows(5);
        jScrollPane_Address.setViewportView(jTextArea_Address);

        jLabel_ShowDateOfBirth.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel_Address.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Address.setText("Address:");

        jLabel_Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentinformationsystem/Icon/Graduation Cap-96.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_InformationLayout = new javax.swing.GroupLayout(jPanel_Information);
        jPanel_Information.setLayout(jPanel_InformationLayout);
        jPanel_InformationLayout.setHorizontalGroup(
            jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InformationLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_DateOfBirth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_BloodGroup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Mobile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_MotherName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_FatherName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_InformationLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_ShowName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_ShowFatherName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_ShowMotherName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_ShowMobile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_ShowId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_InformationLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_ShowDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane_Address, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ShowBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_ShowEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_InformationLayout.createSequentialGroup()
                        .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_InformationLayout.createSequentialGroup()
                                .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_ResultStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_CGPA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_Semester, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_Program, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_ShowSemester, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                    .addComponent(jLabel_ShowCGPA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_ShowResultStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel_ShowProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel_Message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel_InformationLayout.createSequentialGroup()
                        .addComponent(jLabel_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(63, Short.MAX_VALUE))))
        );
        jPanel_InformationLayout.setVerticalGroup(
            jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InformationLayout.createSequentialGroup()
                .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_InformationLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Id, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jLabel_ShowId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jLabel_ShowName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_InformationLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel_ShowFatherName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel_FatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_InformationLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel_MotherName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel_ShowMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Mobile, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(jLabel_ShowMobile, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(jLabel_ShowEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_BloodGroup, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(jLabel_ShowBloodGroup, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_DateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(jLabel_ShowDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_Address, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addGroup(jPanel_InformationLayout.createSequentialGroup()
                                .addComponent(jLabel_Address, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                .addGap(33, 33, 33)))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel_InformationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_InformationLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_Program, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(jLabel_ShowProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_Semester, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(jLabel_ShowSemester, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_CGPA, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(jLabel_ShowCGPA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_ResultStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(jLabel_ShowResultStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(88, 88, 88)
                                .addComponent(jLabel_Message, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addComponent(jSeparator1))))
                .addContainerGap())
            .addGroup(jPanel_InformationLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_InformationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jTabbedPane_Menu.addTab("Information", jPanel_Information);

        javax.swing.GroupLayout jPanel_BaseLayout = new javax.swing.GroupLayout(jPanel_Base);
        jPanel_Base.setLayout(jPanel_BaseLayout);
        jPanel_BaseLayout.setHorizontalGroup(
            jPanel_BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BaseLayout.createSequentialGroup()
                .addComponent(jPanel_Side, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane_Menu))
        );
        jPanel_BaseLayout.setVerticalGroup(
            jPanel_BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BaseLayout.createSequentialGroup()
                .addComponent(jPanel_Top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(jPanel_BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane_Menu)
                    .addComponent(jPanel_Side, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jPanel_Bottom.setBackground(new java.awt.Color(0, 0, 0));
        jPanel_Bottom.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_Bottom.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_Bottom.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Bottom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Bottom.setText("Copyright © Group-4 Spring 2017");

        javax.swing.GroupLayout jPanel_BottomLayout = new javax.swing.GroupLayout(jPanel_Bottom);
        jPanel_Bottom.setLayout(jPanel_BottomLayout);
        jPanel_BottomLayout.setHorizontalGroup(
            jPanel_BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_BottomLayout.setVerticalGroup(
            jPanel_BottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Bottom, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_Bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Make PDF report
    private void jButton_PdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PdfActionPerformed
        try{
            //Variable declaration
            String id = jLabel_ShowId.getText();
            String name = jLabel_ShowName.getText();
            String father_name = jLabel_ShowFatherName.getText();
            String mother_name = jLabel_ShowMotherName.getText();
            String mobile= jLabel_ShowMobile.getText();
            String email = jLabel_ShowEmail.getText();
            String blood_group = jLabel_ShowBloodGroup.getText();
            String birth_date = jLabel_ShowDateOfBirth.getText();
            String address = jTextArea_Address.getText();
            String program = jLabel_ShowProgram.getText();
            String semester = jLabel_ShowSemester.getText();
            String cgpa = jLabel_ShowCGPA.getText();
            String result_status = jLabel_ShowResultStatus.getText();
           
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream("Report.pdf"));
            document.open();
            //document.add(new Paragraph("STUDENT INFORMATION SYSTEM"));
            
            PdfPTable table = new PdfPTable(2);
            PdfPCell cell = new PdfPCell(new Paragraph("Report"));
            cell.setColspan(8);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setPadding(10.0f);
            table.addCell(cell);
        
            table.addCell("ID");
            table.addCell(id);
            table.addCell("Name");
            table.addCell(name);
            table.addCell("Father's Name");
            table.addCell(father_name);
            table.addCell("Mother's Name");
            table.addCell(mother_name);
            table.addCell("Mobile");
            table.addCell(mobile);
            table.addCell("Email");
            table.addCell(email);
            table.addCell("Blood Group");
            table.addCell(blood_group);
            table.addCell("Date of Birth");
            table.addCell(birth_date);
            table.addCell("Address");
            table.addCell(address);
            table.addCell("Program");
            table.addCell(program);
            table.addCell("Semester");
            table.addCell(semester);
            table.addCell("CGPA");
            table.addCell(cgpa);
            table.addCell("Result Status");
            table.addCell(result_status);
           
            document.add(table);
            document.add(new Paragraph(new Date().toString()));
            document.close();
            
            JOptionPane.showMessageDialog(null, "Report Generated");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton_PdfActionPerformed

    //Logout
    private void jButton_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogoutActionPerformed
        //Make confirmation before logout
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out???", "Log Out", JOptionPane.YES_NO_OPTION);
        
        if(confirm == JOptionPane.YES_OPTION)
        {
        this.dispose();
        }
    }//GEN-LAST:event_jButton_LogoutActionPerformed

    //Screenshot
    private void jButton_ScreenshotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ScreenshotActionPerformed
        try{
            saveScreenShot(jPanel_Base, "Student information.png");
            JOptionPane.showMessageDialog(null, "Screenshot Saved");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton_ScreenshotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Logout;
    private javax.swing.JButton jButton_Pdf;
    private javax.swing.JButton jButton_Screenshot;
    private javax.swing.JLabel jLabel_Address;
    private javax.swing.JLabel jLabel_BloodGroup;
    private javax.swing.JLabel jLabel_Bottom;
    private javax.swing.JLabel jLabel_CGPA;
    private javax.swing.JLabel jLabel_DateOfBirth;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_FatherName;
    private javax.swing.JLabel jLabel_Icon;
    private javax.swing.JLabel jLabel_Id;
    private javax.swing.JLabel jLabel_Message;
    private javax.swing.JLabel jLabel_Mobile;
    private javax.swing.JLabel jLabel_MotherName;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_Program;
    private javax.swing.JLabel jLabel_ResultStatus;
    private javax.swing.JLabel jLabel_Semester;
    private javax.swing.JLabel jLabel_ShowBloodGroup;
    private javax.swing.JLabel jLabel_ShowCGPA;
    private javax.swing.JLabel jLabel_ShowDateOfBirth;
    private javax.swing.JLabel jLabel_ShowEmail;
    private javax.swing.JLabel jLabel_ShowFatherName;
    private javax.swing.JLabel jLabel_ShowId;
    private javax.swing.JLabel jLabel_ShowMobile;
    private javax.swing.JLabel jLabel_ShowMotherName;
    private javax.swing.JLabel jLabel_ShowName;
    private javax.swing.JLabel jLabel_ShowProgram;
    private javax.swing.JLabel jLabel_ShowResultStatus;
    private javax.swing.JLabel jLabel_ShowSemester;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JLabel jLabel_Top;
    private javax.swing.JPanel jPanel_Base;
    private javax.swing.JPanel jPanel_Bottom;
    private javax.swing.JPanel jPanel_Information;
    private javax.swing.JPanel jPanel_Side;
    private javax.swing.JPanel jPanel_Title;
    private javax.swing.JPanel jPanel_Top;
    private javax.swing.JScrollPane jScrollPane_Address;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane_Menu;
    private javax.swing.JTextArea jTextArea_Address;
    // End of variables declaration//GEN-END:variables
}
